### ISSUE TITLE
Thumbnails load with a delay for larger number of images in directory

### ISSUE THREAD

**Issue by lcastillo88** [ckfinder/ckfinder#296]
I am reopening issue #214 

I noticed this bug today. I'm using the ASP.NET flavor of CKFinder 3. Folders with a large number of images in them peg the CPU to 100% while thumbnails are being requested. And if you request enough of them at the same time by scrolling (something a user will most certainly do), the CPU stays at 100% for a long time while the CPU tries to load those extra thumbnails. I have to say that this is pretty bad performance. Our team has been working on an upgrade from CKFinder 2 to CKFinder 3 and we never had these issues with the old version. As it stands, the upgrade to CKFinder 3 will not make it to our production servers unless this performance issue is fixed.

**Comment by zaak** [comment]
Hi @lcastillo88. Thanks for reporting the issue. To make it easier to reproduce for us: How many images are in the folder?

**Comment by lcastillo88** [comment]
**There are 777 images in my folder. This exception is thrown in the back end:** 

> 2016-07-12 15:46:51.3783 - FATAL: An unknown error has occured during execution of Thumbnail command.
> EXCEPTION: System.OutOfMemoryException: Out of memory.
>    at System.Drawing.Bitmap.Clone(Rectangle rect, PixelFormat format)
>    at ImageProcessor.Common.Extensions.ImageExtensions.Copy(Image source, AnimationProcessMode animationProcessMode, PixelFormat format)
>    at ImageProcessor.ImageFactory.Load(Stream stream)
>    at CKSource.CKFinder.Connector.Core.Nodes.ImageFile.<GetImageAsync>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at CKSource.CKFinder.Connector.Core.Nodes.ImageFile.<GetImageSizeAsync>d__18.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at CKSource.CKFinder.Connector.Core.Nodes.ImageFile.<GetOrCreateThumbnailAsync>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at CKSource.CKFinder.Connector.Core.Commands.Thumbnail.ThumbnailCommandImpl.<ExecuteAsync>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at CKSource.CKFinder.Connector.Core.CommandHandler.<ExecuteAsync>d__12.MoveNext()


**One other thing is that the UI completely breaks and refuses to load any images if there are more than 1000 images in a single directory. The "loading" gif basically comes up and stays there and an "unknown errror" is thrown in the back end . That's why I backed down the number of files to 777 to finish testing the upgrade. Here is the error thrown in the back end associated with that:**

> 2016-07-12 10:28:07.9702 - FATAL: An unknown error has occured during execution of GetFiles command.
> EXCEPTION: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
>    at CKSource.FileSystem.Path.Combine(String basePath, String[] paths)
>    at CKSource.CKFinder.Connector.Core.Nodes.Folder.<ListFilesAsync>b__10_1(FileInfo fileInfo)
>    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
>    at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
>    at CKSource.CKFinder.Connector.Core.Nodes.Folder.<ListFilesAsync>d__10.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at CKSource.CKFinder.Connector.Core.Commands.GetFiles.GetFilesCommandImpl.<ExecuteAsync>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at CKSource.CKFinder.Connector.Core.CommandHandler.<ExecuteAsync>d__12.MoveNext()
>

**Comment by jswiderski** [comment]
I have also had the same result - W3WP.EXE has taken 100% of CPU usage.

**Comment by karenbridson** [comment]
Any progress on this? We're having this problem with CKFinder 4 too. @wwalc
