### ISSUE TITLE
Symlinks for any folders inside userfiles don't work on Linux environments

### ISSUE THREAD

**Issue by jswiderski** [ckfinder/ckfinder#350]
Let me start by saying that making main user files folder a symlink works. If you use something like `ln -s /destination/folder /opt/pache/htdocs/ckfinder/userfiles` then a working symlink will be created.

If however you try to add symlink for a resource type (files in below example) or even subfolder (test in below example), you will get errors throws (it works fine on Windows): 

`ln -s /home/johnlin/for_sym_linking userfiles/files`
`ln -s /home/johnlin/for_sym_linking userfiles/files/test`

**For `userfiles/files/test`:**
```Fatal error: Uncaught League\Flysystem\NotSupportedException: Links are not supported, encountered link at /opt/lampp/htdocs/ckfinder/userfiles/files/test in /opt/lampp/htdocs/ckfinder/core/connector/php/vendor/league/flysystem/src/NotSupportedException.php:21 Stack trace: #0 /opt/lampp/htdocs/ckfinder/core/connector/php/vendor/league/flysystem/src/Adapter/Local.php(433): League\Flysystem\NotSupportedException::forLink(Object(DirectoryIterator)) #1 /opt/lampp/htdocs/ckfinder/core/connector/php/vendor/league/flysystem/src/Adapter/Local.php(280): League\Flysystem\Adapter\Local->normalizeFileInfo(Object(DirectoryIterator)) #2 /opt/lampp/htdocs/ckfinder/core/connector/php/vendor/league/flysystem-cached-adapter/src/CachedAdapter.php(249): League\Flysystem\Adapter\Local->listContents('files', false) #3 /opt/lampp/htdocs/ckfinder/core/connector/php/vendor/league/flysystem/src/Filesystem.php(270): League\Flysystem\Cached\CachedAdapter->listContents('files', false) #4 /opt/lampp/htdocs/ckfinder/core/connector/php/vendor/cksource/c in /opt/lampp/htdocs/ckfinder/core/connector/php/vendor/league/flysystem/src/NotSupportedException.php on line 21```

**For `userfiles/files/test`:**
`Fatal error: Uncaught CKSource\CKFinder\Exception\AccessDeniedException: Couldn't create resource type directory. Please check permissions. in /opt/lampp/htdocs/ckfinder/core/connector/php/vendor/cksource/ckfinder/src/CKSource/CKFinder/Filesystem/Folder/WorkingFolder.php:135 Stack trace: #0 /opt/lampp/htdocs/ckfinder/core/connector/php/vendor/cksource/ckfinder/src/CKSource/CKFinder/CKFinder.php(134): CKSource\CKFinder\Filesystem\Folder\WorkingFolder->__construct(Object(CKSource\CKFinder\CKFinder)) #1 /opt/lampp/htdocs/ckfinder/core/connector/php/vendor/pimple/pimple/src/Pimple/Container.php(113): CKSource\CKFinder\CKFinder->CKSource\CKFinder\{closure}(Object(CKSource\CKFinder\CKFinder)) #2 /opt/lampp/htdocs/ckfinder/core/connector/php/vendor/cksource/ckfinder/src/CKSource/CKFinder/CKFinder.php(381): Pimple\Container->offsetGet('working_folder') #3 /opt/lampp/htdocs/ckfinder/core/connector/php/vendor/cksource/ckfinder/src/CKSource/CKFinder/Command/CommandAbstract.php(77): CKSource\CKFinder\CKFinder->getWorkingFolder() #4 / in /opt/lampp/htdocs/ckfinder/core/connector/php/vendor/cksource/ckfinder/src/CKSource/CKFinder/Filesystem/Folder/WorkingFolder.php on line 135`

**Comment by jswiderski** [comment]
While you can't create any symlink inside the main user files folder, you can make the main userfiles folder a symlink. This could be used as a workaround even if symlinks were to point to different locations. 
Basically a user can create few local backends each pointing to different location and each holding only a single resource type. That way user could have files located in location A and images in location B.

**Comment by vokiel** [comment]
I think it could be webserver permissions issue. Usually it doesn't have access to folders outside document root. Especially for `/home/different_user/folder`.

This needs more tests, because it may be just the Apache/nginx configuration issue, not CKFinder itself.
